# Generated by Django 4.1 on 2022-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="donation_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
